INSERT INTO categorias (nome) VALUES
('Eletrônicos'),
('Eletrodomésticos'),
('Roupas e Acessórios'),
('Beleza e Cuidados Pessoais'),
('Saúde e Bem-estar'),
('Alimentos e Bebidas'),
('Casa e Decoração'),
('Esportes e Lazer'),
('Automotivo'),
('Brinquedos e Jogos'),
('Papelaria e Escritório'),
('Livros e Mídia'),
('Música e Instrumentos Musicais'),
('Pet Shop'),
('Ferramentas e Construção'),
('Relógios e Óculos'),
('Energia Solar e Sustentabilidade'),
('Segurança e Monitoramento'),
('Viagem e Turismo'),
('Serviços Digitais');



INSERT INTO produtos (nome, descricao, preco, categoria_id) VALUES
('iPhone 15', 'Smartphone com tela OLED de 6,1 polegadas e chip A17.', 5999.00, 1),
('Geladeira Samsung 520L', 'Geladeira de 520 litros com tecnologia de refrigeração no-frost.', 3499.00, 2),
('Tênis Nike Air Max', 'Tênis de corrida com amortecimento Air Max e design moderno.', 499.90, 3),
('Base Líquida L’Oréal', 'Base líquida de alta cobertura com efeito matte e longa duração.', 89.90, 4),
('Multivitamínico One a Day', 'Suplemento diário para melhorar a saúde geral e aumentar a imunidade.', 69.90, 5),
('Cerveja Artesanal IPA', 'Cerveja artesanal com sabor intenso e amargor característico.', 19.90, 6),
('Sofá Retrátil 3 Lugares', 'Sofá retrátil e reclinável, ideal para conforto e elegância na sua sala.', 1599.00, 7),
('Bicicleta MTB Aro 29', 'Bicicleta de mountain bike com suspensão dianteira e aro 29.', 1899.00, 8),
('Kit de Faróis LED para Carro', 'Kit completo de faróis LED para melhoria da visibilidade do seu veículo.', 299.00, 9),
('Jogo de Tabuleiro Catan', 'Jogo de estratégia onde os jogadores constroem e negociam recursos.', 249.90, 10),
('Caderno Universitário 10 Matérias', 'Caderno espiral com 10 matérias e capa personalizada.', 19.90, 11),
('O Senhor dos Anéis - Edição Especial', 'Edição luxuosa com capa dura e ilustrações exclusivas do clássico de J.R.R. Tolkien.', 149.90, 12),
('Violão Yamaha F310', 'Violão acústico de excelente qualidade, ideal para iniciantes.', 799.00, 13),
('Ração Pedigree Sabor Frango', 'Ração seca para cães, sabor frango e com nutrientes balanceados.', 59.90, 14),
('Furadeira Bosch 600W', 'Furadeira elétrica com 600W de potência e velocidade variável.', 299.90, 15),
('Relógio Casio G-Shock', 'Relógio digital e resistente a impactos, ideal para aventuras.', 399.90, 16),
('Kit Solar 200W', 'Painel solar de 200W com inversor e bateria para armazenamento.', 2599.00, 17),
('Câmera de Segurança Arlo Pro 4', 'Câmera de segurança sem fio com alta definição e visão noturna.', 1299.00, 18),
('Mala de Viagem Samsonite', 'Mala resistente e leve, com compartimentos para organização.', 899.00, 19),
('Curso de Marketing Digital', 'Curso online de marketing digital com módulos sobre SEO, Ads e redes sociais.', 499.00, 20);